[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/form/*"
  to = "/form/index.html"
  status = 200

[[redirects]]
  from = "/receipt/*"
  to = "/dashboard/index.html"
  status = 200
